Update README.md
aerogear/offix-android pull request #82
Opened 2019-07-26 04:44 UTC by Lavanyagaur22

Update README.md (docs)

2019-07-26 04:57 UTC, harshithdwivedi commented
Have a look at th comments

2019-07-26 04:57 UTC, harshithdwivedi requested changes

2019-07-26 04:57 UTC, harshithdwivedi commented on docs/README.md
Add a link to the docs below the install header

2019-07-26 04:57 UTC, harshithdwivedi commented on docs/README.md
> +
An an option for installing the library

2019-07-27 12:43 UTC, Lavanyagaur22 commented
@harshithdwivedi This readme will be the first page of our docs.

2019-07-27 14:17 UTC, harshithdwivedi approved these changes

2019-07-27 14:18 UTC, merged